sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t puttybytecoding/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true puttybytecoding/docker-react npm run test
